import { SidebarNav } from '@/components/ui/topbar-nav';
import { UserNav } from '@/components/ui/user-nav';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { HamburgerMenuIcon } from '@radix-ui/react-icons';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sidebarNavItems = [
  {
    title: 'Profile',
    href: '/',
  },
  {
    title: 'Account',
    href: '/test1',
  },
  {
    title: 'Appearance',
    href: '/test2',
  },
  {
    title: 'Notifications',
    href: '/test3',
  },
  {
    title: 'Display',
    href: '/examples/forms/display',
  },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex items-center justify-between max-w-screen-xl px-2 pt-3 mx-auto mb-3'>
          <SidebarNav items={sidebarNavItems} className='hidden md:flex' />
          <HamburgerMenuIcon className='flex md:hidden' />
          <UserNav />
        </div>
        {children}
      </body>
    </html>
  );
}
