import type { Metadata } from 'next';
import { Athiti } from 'next/font/google';

import './globals.css';
import { Suspense } from 'react';

const inter = Athiti({ weight: ['500', '600', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
