import { HamburgerMenuIcon } from '@radix-ui/react-icons';
import type { Metadata } from 'next';

import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import SidebarNav from '@/components/ui/sidebar-nav';
import { TopBarNav } from '@/components/ui/topbar-nav';
import { UserNav } from '@/components/ui/user-nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sidebarNavItems = [
  {
    title: 'User',
    href: '/dashboard/users',
  },
  {
    title: 'Role',
    href: '/dashboard/roles',
  },
  {
    title: 'Organization',
    href: '/dashboard/organization',
  },
  {
    title: 'Invoice',
    href: '/dashboard/invoices',
  },
  {
    title: 'Project',
    href: '/dashboard/projects',
  },
];

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className='flex items-center justify-between mx-6 my-6 max-w-screen'>
        <div>
          <TopBarNav items={sidebarNavItems} className='hidden md:flex' />
          <Sheet>
            <SheetTrigger>
              <HamburgerMenuIcon className='flex md:hidden' />
            </SheetTrigger>
            <SheetContent className='w-[300px]' side='left'>
              <SidebarNav items={sidebarNavItems} />
            </SheetContent>
          </Sheet>
        </div>
        <h1 className='text-2xl text-center md:-mt-4'>Skill</h1>

        <UserNav />
      </div>
      {children}
    </>
  );
}
